version: '3.2'

services:

  ijson:
    image: lega911/ijson
    container_name: ijson
    ports:
      - 8001:8001

  mysql:
    image: mysql:5.7
    container_name: laravel-template-mysql
    ports:
      - 3317:3306
    volumes:
      - ./docker/mysql/storage:/var/lib/mysql
