#!/usr/bin/env php
<?php

function getEnvironment($key, $default)
{
    return getenv($key) ? getenv($key) : $default;
}

function getAppDebug()
{
    if (getEnvironment('APP_ENV', 'development') === 'development') {
        return 'true';
    }

    return 'false';
}

function getAppKey()
{
    $path = (__DIR__) . '/.env';

    if (!is_file($path)) {
        return '';
    }

    $content = file_get_contents($path);

    $appKey = '';
    foreach (explode("\n", $content) as $item) {
        if (strpos($item, 'APP_KEY=') !== false) {
            $appKey = str_replace('APP_KEY=', '', $item);
            break;
        }
    }

    return $appKey;
}

$content = [
    'APP_NAME=' . getEnvironment('PROJECT_ALIAS', 'panel'),
    'APP_ENV=' . getEnvironment('APP_ENV', 'development'),
    'APP_KEY=' . getAppKey(),
    'APP_DEBUG=' . getAppDebug(),
    'APP_URL=http://localhost',
    '',
    'LOG_CHANNEL=stack',
    '',
    'DB_CONNECTION=mysql',
    'DB_HOST=' . getEnvironment('MYSQL_HOST', '127.0.0.1'),
    'DB_PORT=' . getEnvironment('MYSQL_PORT', '3306'),
    'DB_DATABASE=' . getEnvironment('MYSQL_DATABASE', 'example'),
    'DB_USERNAME=' . getEnvironment('MYSQL_USER', 'root'),
    'DB_PASSWORD=' . getEnvironment('MYSQL_PASSWORD', ''),
    '',
    'PANEL_ALIAS=' . getEnvironment('PANEL_ALIAS', 'panel'),
    'IJSON_HOST=' . getEnvironment('IJSON_HOST', ''),
    '',
    'CONTROL_PANEL_DISABLE=' . getEnvironment('CONTROL_PANEL_DISABLE', 'no'),
    'AUTHORIZATION_DISABLE=' . getEnvironment('AUTHORIZATION_DISABLE', 'yes'),
    'DATABASE_SEEDER_DISABLE=' . getEnvironment('DATABASE_SEEDER_DISABLE', 'no'),
    '',
    'BROADCAST_DRIVER=log',
    'CACHE_DRIVER=file',
    'QUEUE_CONNECTION=sync',
    'SESSION_DRIVER=file',
    'SESSION_LIFETIME=120',
    '',
    'REDIS_HOST=127.0.0.1',
    'REDIS_PASSWORD=null',
    'REDIS_PORT=6379',
    '',
    'MAIL_MAILER=smtp',
    'MAIL_HOST=smtp.mailtrap.io',
    'MAIL_PORT=2525',
    'MAIL_USERNAME=null',
    'MAIL_PASSWORD=null',
    'MAIL_ENCRYPTION=null',
    'MAIL_FROM_ADDRESS=null',
    'MAIL_FROM_NAME="${APP_NAME}"',
    '',
    'AWS_ACCESS_KEY_ID=',
    'AWS_SECRET_ACCESS_KEY=',
    'AWS_DEFAULT_REGION=us-east-1',
    'AWS_BUCKET=',
    '',
    'PUSHER_APP_ID=',
    'PUSHER_APP_KEY=',
    'PUSHER_APP_SECRET=',
    'PUSHER_APP_CLUSTER=mt1',
    '',
    'MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"',
    'MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"'
];

file_put_contents((__DIR__) . '/.env', implode("\n", $content));



